### PR TITLE
build with docker

### PR DESCRIPTION
**Pull request by cskiraly**
Docker now supports multi-stage build, the only reason we've used Rockerfiles. 

Moreover, in the Rockerfile, we were using alpine, but this leads to
https://github.com/Agile-IoT/agile-ui/issues/21

Further, using alpine would only make sense if we would apply it on all node based images. Otherwise, if there are other node images using debian a basis, there is no space saving on the platform level.

### CODE REVIEW

**Comment by craigmulligan** [comment]
Hmm but you haven't added docker build steps? I'm okay with this in general because we are moving things back to docker but it's now ~ 250mb rather than 19. If that's okay then lgtm

**Comment by cskiraly** [comment]
I think I was too synthetic in my description above :-) 
Going from 250 (which might be, to take an example, something like 240 of base image + 10 of new layers) to 19 (9 of base image + 10 of new layers) only makes sense if the base image would not be needed then. However, since that 240 MB base image is used in other components, you are actually increasing the size of the whole distribution by introducing a new, even if small, base image.
This is not to say that it does not make sense, but we should introduce new base images coherently to have the gain in disk usage. There might also be other advantages to smaller images, e.g. cheaper creation of new containers, but these depend on the storage backend, etc.
Finally, regarding multi-stage build: we will use it, but it seems too early. I'm in fact thinking of rolling back on it also for other containers, because it is still too hard to have Docker 17.05-ce support on platforms. Once that becomes simple, we can move on.

**Comment by craigmulligan** [comment]
Yea I understand the sharing of base images, trying to show how small we could get it. What I'm saying here is that we don't need the whole node.js runtime because it's just serving static assets, right now we are shipping node.js + build deps which is much much bigger than it needs to be. 

But If we are okay with that then 👍, it makes things simpler.

**Comment by cskiraly** [comment]
Correct, still I think we are OK for the moment. We will do multi-stage once it is fairly available on platforms, at least on what we rely on. Then, however, we should also find a real solution to https://github.com/Agile-IoT/agile-ui/issues/21

**Pull request merged**
