### PR TITLE
Unqiue deviceTypes per device

### PR DESCRIPTION
**Pull request by craigmulligan**
Connects to #27

Change-Type: patch

### CODE REVIEW

**Comment by craigmulligan** [comment]
cc @cskiraly. I still need to test later, but should work fine.

**Comment by cskiraly** [comment]
I have tested compiling from source. I still see it showing all device types for each device.

**Comment by craigmulligan** [comment]
@cskiraly working for me, is it possible you built it from master and not this branch?

**Comment by craigmulligan** [comment]
screen shot 2017-06-14 at 12 27 39
screen shot 2017-06-14 at 12 27 51

**Pull request merged**
