### PR TITLE
use recommmended base image

### PR DESCRIPTION
**Pull request by cskiraly**
Would be better to use the new image hierarchy and the AGILE recommended tag.

### CODE REVIEW

**Comment by craigmulligan** [comment]
Looks good, could you add `Change-type: patch` to the commit footer?

**Comment by cskiraly** [comment]
I see a build error on Travis, but I think it is just a timeout due to build being too long and too silent, not producing new lines for more than 10 minutes.

**Comment by craigmulligan** [comment]
@cskiraly true, the weird thing is that the PR isn't setting a $DOCKER_TAG. see : https://travis-ci.org/Agile-IoT/agile-ui/jobs/242430371#L277 .. not sure why

UPDATE: nvm, I was looking at the run job.

**Comment by craigmulligan** [comment]
this was included in #37

**Pull request closed without merging**
